# NumPy Basics

Algumas das coisas oferecidas por NumPy:
- ndarray, um array multidimensional eficiente que fornece operações aritméticas orientadas a arrays rápidas e recursos de transmissão flexíveis.
- Funções matemáticas para operações rápidas em matrizes inteiras de dados sem precisar escrever loops.
- Ferramentas para ler/escrever dados de array em disco e trabalhar com arquivos mapeados em memória.
- Capacidades de álgebra linear, geração de números aleatórios e transformada de Fourier
- API C para conectar NumPy com bibliotecas escritas em C, C++ ou FORTRAN  

NumPy é projetado para ser eficiente em grandes matrizes de dados.
- Ele armazena internamente dados em um bloco contíguo de memória de modo que os seus algoritmos (escritos em C) possam operar nesse bloco.
- Os arrays NumPy usam muito menos memória do que as sequências nativas do Python.
- Operações NumPy realizam cálculos complexos em arrays inteiros sem a necessidade de loops `for`, que pode ser lento para sequências grandes.
- NumPy é mais rápido que o código regular do Python porque seus algoritmos baseados em C evitam a sobrecarga presente em  código interpretado.
- Os algoritmos baseados em NumPy são geralmente de 10 a 100 vezes mais rápidos (ou mais) do que seus equivalentes em Python puro e usam significativamente menos memória.

## ndarray

O **ndarray** é um objeto de array multidimensional (N-dimensões). Com ele, é possível realizar operações matemáticas em blocos inteiros de dados como se fossem valores escalares:

In [1]:
import numpy as np

In [2]:
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])

In [3]:
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [4]:
data * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [5]:
data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

O ndarray é um container multidimensional homogêneo, ou seja, todos os elementos precisam ser do mesmo tipo. Cada objeto possui um atributo `shape`, uma tupla indicando o tamanho de cada dimensão, e um `dtype`, um objeto descrevendo o tipo de dado do array:

In [6]:
data.shape

(2, 3)

In [7]:
data.dtype

dtype('float64')