# NumPy Basics

Algumas das coisas oferecidas por NumPy:
- ndarray, um array multidimensional eficiente que fornece operações aritméticas orientadas a arrays rápidas e recursos de transmissão flexíveis.
- Funções matemáticas para operações rápidas em matrizes inteiras de dados sem precisar escrever loops.
- Ferramentas para ler/escrever dados de array em disco e trabalhar com arquivos mapeados em memória.
- Capacidades de álgebra linear, geração de números aleatórios e transformada de Fourier
- API C para conectar NumPy com bibliotecas escritas em C, C++ ou FORTRAN  

NumPy é projetado para ser eficiente em grandes matrizes de dados.
- Ele armazena internamente dados em um bloco contíguo de memória de modo que os seus algoritmos (escritos em C) possam operar nesse bloco.
- Os arrays NumPy usam muito menos memória do que as sequências nativas do Python.
- Operações NumPy realizam cálculos complexos em arrays inteiros sem a necessidade de loops `for`, que pode ser lento para sequências grandes.
- NumPy é mais rápido que o código regular do Python porque seus algoritmos baseados em C evitam a sobrecarga presente em  código interpretado.
- Os algoritmos baseados em NumPy são geralmente de 10 a 100 vezes mais rápidos (ou mais) do que seus equivalentes em Python puro e usam significativamente menos memória.

## ndarray

O **ndarray** é um objeto de array multidimensional (N-dimensões). Com ele, é possível realizar operações matemáticas em blocos inteiros de dados como se fossem valores escalares:

In [1]:
import numpy as np

In [2]:
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])

In [3]:
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [4]:
data * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [5]:
data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

O ndarray é um container multidimensional homogêneo, ou seja, todos os elementos precisam ser do mesmo tipo. Cada objeto possui um atributo `shape`, uma tupla indicando o tamanho de cada dimensão, e um `dtype`, um objeto descrevendo o tipo de dado do array:

In [6]:
data.shape

(2, 3)

In [7]:
data.dtype

dtype('float64')

## Criando ndarrays

A função `array` cria um ndarray a partir de qualquer sequência:

In [6]:
data1 = [5, 7.5, 8, 0 , 1]

In [8]:
arr1 = np.array(data1)

In [9]:
arr1

array([5. , 7.5, 8. , 0. , 1. ])

In [10]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [12]:
arr2 = np.array(data2)

In [13]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [14]:
arr2.ndim # number of dimensions

2

In [15]:
arr2.shape

(2, 4)

NumPy irá deduzir o tipo de dado caso não seja especificado.

In [17]:
arr1.dtype

dtype('float64')

In [18]:
arr2.dtype

dtype('int64')

As funções `zeros` e `ones` criam matrizes de 0s e 1s, respectivamente:

In [19]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Diferente da função `zeros`, a função `empty` cria uma matriz sem valores iniciados. Isso significa que ela apenas reserva espaço na memória para a matriz. Os valores iniciais são considerados "lixo".

In [25]:
np.empty(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

A função `arange` é semelhante a função `range` do Python, mas retorna um ndarray:

In [27]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Tipos de dados para ndarrays

É possível especificar o tipo de dado durante a criação de um ndarray. Isso é bastante útil quando estamos lidando com um dataset muito grande e queremos otimizar o seu armazenamento na memória.

In [30]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

In [32]:
arr1.dtype

dtype('float64')

In [33]:
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [34]:
arr2.dtype

dtype('int32')

Os tipos numéricos seguem o mesmo formato: o nome do tipo, como `float` ou `int`, seguido do número de bits de cada elemento.

| Tipo            | Alias        | Descrição
------------------|--------------|----------------------------------------------
`int8`, `uint8`   | `i1`, `u1`   | Signed e Unsigned 8-bit (1 byte) integer type
`int16`, `uint16` | `i2`, `u2`   | Signed e Unsigned 16-bit integer type
`int32`, `uint32` | `i4`, `u4`   | Signed e Unsigned 32-bit integer type
`int64`, `uint64` | `i8`, `u8`   | Signed e Unsigned 64-bit integer type
`float16`         | `f2`         | Half-precision floating point
`float32`         | `f4` or `f`  | Standard single-precision floating point; compatible with C float
`float64`         | `f8` or `d`  | Standard double-precision floating point; compatible with C double and Python float
`float128`        | `f16` or `g` | Extended-precision floating point
`complex64`       | `c8`         | Complex numbers represented by two 32 floats
`complex128`      | `c16`        | Complex numbers represented by two 64 floats
`complex256`      | `c32`        | Complex numbers represented by two 128 floats
`bool`            | ?            | Boolean type storing `True` and `False` values
`bytes_ `         | S            | Fixed-length ASCII string type (1 byte per character); for example, to create a string data type with length 10, use `S10`
`str_`            | U            | Fixed-length Unicode type (number of bytes platform specific); same specification semantics as string_ (e.g., `U10`)

A função `astype` converte (*cast*) uma matriz de um tipo para outro:

In [35]:
arr = np.array([1, 2, 3, 4, 5])

In [36]:
arr.dtype

dtype('int64')

In [37]:
float_arr = arr.astype(np.float64)

In [38]:
float_arr

array([1., 2., 3., 4., 5.])

In [39]:
float_arr.dtype

dtype('float64')

Se a converção envolver um tipo `float` para um tipo `int`, a parte decimal é removida:

In [40]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [41]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

Convertendo uma string para um formato numérico:

In [50]:
numeric_strings = np.array(["1.25", "-9.6", "42"], dtype=np.bytes_)

In [51]:
numeric_strings.astype(np.float32)

array([ 1.25, -9.6 , 42.  ], dtype=float32)

A função `astype` sempre cria um novo array (uma cópia dos dados).

## Aritmética com ndarrays

Qualquer aritmética entre arrays de mesmo tamanho aplica a operação elemento a elemento:

In [3]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [5]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [10]:
arr + arr

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [12]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

Operações aritmética com escalares propaga o escalar para cada elemento:

In [14]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [15]:
arr ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

Comparação entre arrays de mesmo tamanho produz outro array com booleanos:

In [16]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [17]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [18]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

## Indexing e slicing

In [20]:
arr = np.arange(10)

In [21]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
arr[5]

np.int64(5)

In [23]:
arr[5:8]

array([5, 6, 7])

É possível assinalar um valor para uma seleção (broadcasting):

In [24]:
arr[5:8] = 12

Ao contrário das listas nativas em Python, seleções em arrays NumPy é apenas uma visão do array original. Assim, as alterações em um slicing são propagadas para o array original.

In [25]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

Se quisermos copiar uma seleção, precisamos fazer isso explicitamente:

In [26]:
arr[5:8].copy()

array([12, 12, 12])

Acessando elementos de um array multi-dimensional:

In [41]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [28]:
arr2d[2]

array([7, 8, 9])

In [29]:
arr2d[0][2]

np.int64(3)

Modo alternativo de indexar multi-dimensões:

In [30]:
arr2d[0, 2]

np.int64(3)

Slicing de uma matriz multi-dimensional:

In [32]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
arr2d[:2] # select first two rows

array([[1, 2, 3],
       [4, 5, 6]])

Usando múltiplas seleções, uma para cada dimensão:

In [35]:
arr2d[:2, 1:] # first two rows, columns 2 and 3

array([[2, 3],
       [5, 6]])

Misturando index e slicing:

In [37]:
arr2d[1, :2] # second row, first two columns

array([4, 5])

In [38]:
arr2d[:2, 2] # first two rows, third column

array([3, 6])

In [39]:
arr2d[:, :1] # all rows, first column

array([[1],
       [4],
       [7]])

Atribuindo um valores:

In [44]:
arr2d[1] = 0 # set all values in second row to 0

In [43]:
arr2d

array([[1, 2, 3],
       [0, 0, 0],
       [7, 8, 9]])

In [48]:
arr2d[:2, 1:] = -1 # set first two rows, columns 2 and 3 to 01

In [49]:
arr2d

array([[ 1, -1, -1],
       [ 0, -1, -1],
       [ 7,  8,  9]])

## Índices booleanos

É possível comparar uma matriz inteira com um elemento, de modo que o resultado seja uma nova matriz com valores booleanos:

In [3]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])

In [4]:
names == "Bob"

array([ True, False, False,  True, False, False, False])

É possível usar uma matriz de booleanos para indexar outra matriz (ambas precisam ter o mesmo tamanho):

In [7]:
data = np.array([1, 2, 3, 4, 5, 6, 7])

In [21]:
data[names == "Bob"]

array([1, 4])

Se assinalarmos o resultado em uma variável, criaremos uma cópia dos dados:

In [19]:
new_data = data[names == "Bob"]

In [20]:
new_data

array([1, 4])

O operador `~` pode ser usado como negação:

In [10]:
names != "Bob"

array([False,  True,  True, False,  True,  True,  True])

In [11]:
~(names == "Bob") # equivalent to names != "Bob"

array([False,  True,  True, False,  True,  True,  True])

In [15]:
cond = names == "Bob"

In [16]:
~cond

array([False,  True,  True, False,  True,  True,  True])

Combinando múltiplas condições booleanas com os operadores `&` (and) e `|` (ou):

In [13]:
mask = (names == "Bob") | (names == "Will")

In [14]:
mask

array([ True, False,  True,  True,  True, False, False])

In [17]:
data[mask]

array([1, 3, 4, 5])

Atribuindo valores utilizando indexes booleanos:

In [23]:
data[data < 5] = 0

In [24]:
data

array([0, 0, 0, 0, 5, 6, 7])

Uma matriz booleana pode ser usada para indexar matrizes multi-dimensionais:

In [25]:
data2 = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2], [-12, -4], [3, 4]])

In [27]:
data2[names == "Bob"]

array([[4, 7],
       [0, 0]])

In [29]:
data2[data2 < 0]

array([ -5, -12,  -4])

In [30]:
data2[data2 < 0] = 0

In [31]:
data2

array([[4, 7],
       [0, 2],
       [0, 6],
       [0, 0],
       [1, 2],
       [0, 0],
       [3, 4]])

Combinando matriz booleana e slicing para indexar outra matriz:

In [34]:
data2[names == "Bob", 1:] # select rows where names == "Bob" and column 2 (slice)

array([[7],
       [0]])

In [35]:
data2[names == "Bob", 1] # select rows where names == "Bob" and column 2 (single element)

array([7, 0])

## Fancy indexing

É possível indexar uma matriz utilizando uma matriz uni-dimensional de inteiros:

In [51]:
arr = np.zeros((8, 4))

In [52]:
for i in range(8):
  arr[i] = i

In [53]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [59]:
arr[[4, 3, 0, 6]] # select rows 4, 3, 0, 6

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

Ao usar inteiros negativos, indexamos a partir do final:

In [58]:
arr[[-3, -5, -7]] # select rows 5, 3, 1 from the end

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

Ao indexar com múltiplas matrizes de inteiro, selecionamos os valores que correspondem a cada tupla de índices:

In [57]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]] # select elements (1, 0), (5, 3), (7, 1), (2, 2)

array([1., 5., 7., 2.])

Ao assinar o resultado a uma variável, criamos uma cópia dos dados:

In [64]:
arr2 = arr[[1, 5, 7, 2], [0, 3, 1, 2]]

In [65]:
arr2

array([1., 5., 7., 2.])

# Universal Functions (ufunc)

Funções universais são funções que executam operações elemento a elemento em um ndarray. Existem funções unárias, que aceitam um único array, e funções binárias, que aceitam dois arrays e devolvem um ou mais arrays.

In [2]:
arr = np.arange(10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# Exemplo de função unária
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [8]:
x = np.arange(5)
y = np.arange(5)
x, y

(array([0, 1, 2, 3, 4]), array([0, 1, 2, 3, 4]))

In [7]:
# Exemplo de função binária
np.add(x, y)

array([0, 2, 4, 6, 8])

Algumas funções unárias incluem:
| Função                | Descrição
-----------------------|-----------------------------------------------
`abs`, `fabs`          | Compute the absolute value element-wise for integer, floating-point, or complex values
`sqrt`                 | Compute the square root of each element (equivalent to `arr ** 0.5`)
`square`               | Compute the square of each element (equivalent to `arr ** 2`)
`exp`                  | Compute the exponent eˣ of each element
`log`, `log10`, `log2` | Natural logarithm (base e), log base 10 and log base 2, respectively
`sign`                 | Compute the sign of each element: `1` (positive), `0` (zero), or `–1` (negative)
`ceil`                 | Compute the ceiling of each element (the smallest integer greater than or equal to that number)
`floor`                | Compute the floor of each element (the largest integer less than or equal to each element)
`rint`                 | Round elements to the nearest integer, preserving the dtype
`modf`                 | Return fractional and integral parts of array as separate arrays
`isnan`                | Return Boolean array indicating whether each value is NaN (Not a Number)
`isfinite`, `isinf`    | Return Boolean array indicating whether each element is finite or infinite, respectively
`cos`, `cosh`, `sin`, `sinh`, `tan`, `tanh` | Regular and hyperbolic trigonometric functions
`arccos`, `arccosh`, `arcsin`, `arcsinh`, `arctan`, `arctanh` | Inverse trigonometric functions
`logical_not`          | Compute truth value of `not x` element-wise (equivalent to `~arr`)

Algumas funções binárias incluem:
| Função                 | Descrição
-------------------------|-----------------------------------------------
`add`                    | Add corresponding elements in arrays
`subtract`               | Subtract elements in second array from first array
`multiply`               | Multiply array elements
`divide`, `floor_divide` | Divide or floor divide (truncating the remainder)
`power`                  | Raise elements in first array to powers indicated in second array
`maximum`, `fmax`        | Element-wise maximum; `fmax` ignores `NaN`
`minimum`, `fmin`        | Element-wise minimum; `fmin` ignores `NaN`
`mod`                    | Element-wise modulus (remainder of division)
`copysign`               | Copy sign of values in second argument to values in first argument
`greater`, `greater_equal`, `less`, `less_equal`, `equal`, `not_equal` | Perform element-wise comparison, yielding Boolean array (equivalent to infix operators `>`, `>=`, `<`, `<=`, `==`, `!=`)
`logical_and`            | Compute element-wise truth value of AND (`&`) logical operation
`logical_or`             | Compute element-wise truth value of OR (`|`) logical operation
`logical_xor`            | Compute element-wise truth value of XOR (`^`) logical operation

# Array-Oriented Programming
NumPy nos permite expressar diversas operações de dados como expressões de array concisas que, de outra maneira, necessitaria de loops. Essa prática de substituir loops por expressões de array é chamado de **vetorização**.

A função `np.where` possui o mesmo efeito que uma operação ternária (`x if cond else y`):

In [13]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])

In [14]:
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])

In [11]:
cond = np.array([True, False, True, True, False])

In [15]:
np.where(cond, xarr, yarr)

array([1.1, 2.2, 1.3, 1.4, 2.5])

Também podemos retornar valores escalares:

In [17]:
arr = np.array([-.1, 0, .1, .2, -.3, .4])

In [19]:
np.where(arr > 0, 1, arr)

array([-0.1,  0. ,  1. ,  1. , -0.3,  1. ])

In [18]:
np.where(arr > 0, 1, -1)

array([-1, -1,  1,  1, -1,  1])

Os arrays possuem alguns métodos matemáticos e estatísticos, como `sum`, `mean`, `min`, `max`:

In [39]:
arr = np.array([1, 2, 3, 4, 5])

In [21]:
arr.sum() # soma de todos os elementos

np.int64(15)

In [41]:
# Número de ocorrências de valores maiores que 3
(arr > 3).sum()

np.int64(2)

In [22]:
arr.mean() # média aritmética

np.float64(3.0)

In [23]:
arr.min() # menor valor

np.int64(1)

In [24]:
arr.max() # maior valor

np.int64(5)

O método `cumsum` retorna a soma acumulada dos elementos do array:

In [29]:
arr = np.array([
  [0, 1, 2],
  [3, 4, 5],
  [6, 7, 8]
])

In [26]:
arr.cumsum() # soma acumulada de todos os elementos (i.e. 0, 0+1, 0+1+2, 0+1+2+3, ...)

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36])

In [30]:
arr.cumsum(axis=0) # soma acumulada de cada coluna (i.e. 0, 1, 2; 0+3, 1+4, 2+5; 0+3+6, 1+4+7, 2+5+8)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]])

In [32]:
arr.cumsum(axis=1) # soma acumulada de cada linha (i.e. 0, 0+1, 0+1+2; 3, 3+4, 3+4+5; 6, 6+7, 6+7+8)

array([[ 0,  1,  3],
       [ 3,  7, 12],
       [ 6, 13, 21]])

Gerando números aleatórios (pseudo-aleatórios na verdade) com `np.random` (muito mais eficiente que o módulo built-in do Python, que gera um único número por vez):

In [33]:
rng = np.random.default_rng(seed=12345) # o seed é opcional e serve para garantir que os resultados sejam reproduzíveis

In [35]:
rng.integers(0, 10, 10) # gera 10 números inteiros aleatórios entre 0 e 10

array([7, 2, 9, 9, 7, 6, 1, 0, 2, 4])

In [34]:
rng.standard_normal(10) # gera 10 números aleatórios com distribuição normal padrão

array([-1.42382504,  1.26372846, -0.87066174, -0.25917323, -0.07534331,
       -0.74088465, -1.3677927 ,  0.6488928 ,  0.36105811, -1.95286306])

In [36]:
rng.uniform(0, 1, 10) # gera 10 números aleatórios com distribuição uniforme entre 0 e 1

array([0.88647992, 0.6974535 , 0.32647286, 0.73392816, 0.22013496,
       0.08159457, 0.1598956 , 0.34010018, 0.46519315, 0.26642103])

Os métodos `any` e `all` verifica a ocorrência de valores verdadeiros (`True`):

In [42]:
bools = np.array([False, False, True, False])

In [43]:
bools.any() # retorna True se pelo menos um valor for True

np.True_

In [44]:
bools.all() # retorna True se todos os valores forem True

np.False_

> **Nota**
>
> Qualquer valor não-zero é considerado `True`.

O método `sort` ordena um array *in-place*:

In [45]:
arr = np.array([5, 2, 3, 4, 1])

In [46]:
arr.sort()

In [48]:
arr

array([1, 2, 3, 4, 5])

In [50]:
# Para ordenar sem modificar o array original, use np.sort
np.sort(arr)

array([1, 2, 3, 4, 5])

Ordenando um array multidimensional:

In [52]:
arr = np.array([
  [5, 3, 1],
  [2, 6, 4],
  [7, 9, 8]
])

In [53]:
arr.sort(axis=0) # ordena cada coluna

In [54]:
arr

array([[2, 3, 1],
       [5, 6, 4],
       [7, 9, 8]])

In [55]:
arr.sort(axis=1) # ordena cada linha

In [56]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
# Para ordenar sem modificar o array original, use np.sort
np.sort(arr, axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

A função `np.unique` retorna um array ordenado e sem valores duplicados:

In [58]:
values = np.array([6, 0, 0, 3, 2, 5, 6])

In [59]:
np.unique(values)

array([0, 2, 3, 5, 6])

A função `np.isin` verifica a existência de valores em um array e retorna um array de booleanos:

In [61]:
np.isin(values, [2, 3, 6]) # verifica se os elementos de values estão contidos em [2, 3, 6]

array([ True, False, False,  True,  True, False,  True])